name: Tweakly-nano33ble
on: [push, pull_request]
jobs:
  Tweakly-nano33ble:
    strategy:
      matrix:
        arduino-platform: ["arduino:mbed"]
        include:
          - arduino-platform: "arduino:mbed"
            fqbn: "arduino:mbed:nano33ble"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
          arduino-cli lib install Tweakly
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./examples/01.Basic/Analog_input_Pad/Analog_input_Pad.ino
